### ISSUE TITLE
Running testers in parallel doesn't work

### ISSUE THREAD

**Issue by grebe** [ucb-art/pfb#1]
[This line in the tester](https://github.com/ucb-art/pfb/blob/master/src/test/scala/PFBSpec.scala#L100) doesn't work. Get rid of the toParArray and everything works.

**Comment by chick** [comment]
I can't see what's going on there.  I'm out tomorrow, I'll be back in soda on Thursday

**Comment by grebe** [comment]
Closed by 72e6a8e1be617eaf10a81ce8c59789cf1d988c97 or some commit around then
